### ISSUE TITLE
table_name_template {{._timestamp.Format "YYYY_MM"}} not formating

### ISSUE THREAD

**Issue by lutek** [jitsucom/eventnative#110]
Using template name for table doesn't work in postgres destination 
```
    data_layout:
      table_name_template: 'events_{{._timestamp.Format "YYYY_MM"}}' 
```

_timestamp value from database: 2020-11-12 12:46:24.337047

should be: "events_2020_11"
but creating "events_yyyy_mm"

**Comment by xtreding** [comment]
Hi @lutek!
EventNative uses Golang time layouts
![image](https://user-images.githubusercontent.com/18486255/98962749-fd5ae480-2517-11eb-9448-93aafdf6f97f.png)

In your case, you should configurate:
```
data_layout:
      table_name_template: 'events_{{._timestamp.Format "2006_01"}}'
``` 

For more information please visit:
[Our documentation page](https://docs.eventnative.org/configuration-1/configuration/schema-and-mappings#step-4-table-name-selection) (I've fixed it)
[Golang documentation page](https://golang.org/src/time/format.go)

**Comment by lutek** [comment]
Thanks,
I suggested formatting from the documentation.

**Comment by xtreding** [comment]
@lutek Thank you!
