### ISSUE TITLE
Represent string columns as Text

### ISSUE THREAD

**Issue by xtreding** [jitsucom/eventnative#126]
### Problem

At present **EventNative** creates string columns as `character varying(8192)` and cuts strings which are greater.
Also, **EventNative** represents arrays as strings, and in this case, the array value might become invalid.

### Solution

EventNative should create strings columns as `Text` instead of `character varying(8192)`.

**Comment by vklimontovich** [comment]
Closing in favor of #131 which supersedes this issue
