### ISSUE TITLE
Delete and bulk insert operation

### ISSUE THREAD

**Issue by vklimontovich** [jitsucom/eventnative#127]
## Problem

For syncing from third-party sources, EventNative should be able to run 'bulk replace' operations. Bulk replace is
a equivalent of

```sql
DELETE from destination where field=value;
INSERT INTO destination VALUES (...);
...
INSERT INTO destination VALUES (...);
```

executed in a single transaction

## Solution

EventNative should have an insert and replace API with the following payload:

```json
{
  "replace": {
    "where": [
      {
        "field": "value"
      }
    ]
  },
  "__destiation_table": "<table>",
  "__primary_key": "<field>",
  "events": [
    {}, {}
  ]
}
```

Payload should not go through stream pipeline but be written as synchronous call.

### Scope

The scope of this issue include:
 * Adding (optional) delete and bulk insert operations into Destination interface
 * Change sync executor into new API: where section should contain __chunk='<ChunkId>'
 * Save __chunk with every event

**Comment by akhtyamovrr** [comment]
Implemented at #149
