### ISSUE TITLE
Externalize EventNative configuration

### ISSUE THREAD

**Issue by vklimontovich** [jitsucom/eventnative#166]
### Problem

Currently, EventNative can't be started in "pure" docker environment. A local file with configuration should be provided (and mounted). Some users requested to be able to put configuration somewhere else and pass location through environment variable.

### Solution

Two features are required to solve the problem:
 - ./eventnative -cfg https://url should work. The parameter should accept urls as well. Let's support basic auth as well (via https://user:password@host syntax
 - Docket image should accept optional env variable CONFIG_LOCATION. If it's set EN should be started with ./eventnative -cfg $CONFIG_LOCATION

**Comment by clementgalopin** [comment]
Hi guys, what is the estimated date of delivery for this feature? Thanks!

**Comment by xtreding** [comment]
Hi @clementgalopin!
This task is implemented and available since [1.28.2](https://github.com/jitsucom/eventnative/releases/tag/v1.28.2)!
