### ISSUE TITLE
Redis driver

### ISSUE THREAD

**Issue by akhtyamovrr** [jitsucom/eventnative#175]
### Problem

Redis is popular storage which we also use to keep configurations (#160). It's nice to have a way to load data from Redis to other storages (in case of migration of some statistics purposes)

### Solution

Implement driver to migrate events from Redis to destinations.

**Comment by guillaumemeyer** [comment]
Wouldn't it be great to be able to use Redis instead of etcd as a state service for cluster?
It's far more common and easy to use and deploy...

**Comment by akhtyamovrr** [comment]
Hi, @guillaumemeyer ! Thank you for your suggestion! It's possible, we just need time to implement this. Feel free to create a feature request (or we will create one ourselves after discussion). It's great to have feedback from you about our product!
