### ISSUE TITLE
Implement material style floating labels

### ISSUE THREAD

**Issue by vklimontovich** [jitsucom/eventnative#204]
### Problem

The current approach to labeling consumes too much screen space. It would be nice to use material style [floating labels](https://material.io/develop/web/supporting/floating-label) for some components. Unfortunately, antd doesn't have a component for that

### Solution

- Implement a component with floating labels
- Switch the login and registration form to this component

See [SO example](https://stackoverflow.com/questions/58699830/floating-labels-using-react-and-ant-design)

**Comment by alexhovansky** [comment]
PR - https://github.com/jitsucom/eventnative-manager/pull/21
